/*
 * generated by Xtext
 */
package com.yakindu.sct.domain.scenario;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ScenarioTextStandaloneSetup extends ScenarioTextStandaloneSetupGenerated{

	public static void doSetup() {
		new ScenarioTextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

