/*
 * generated by Xtext
 */
package com.yakindu.sct.domain.scenario.scoping;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class ScenarioTextScopeProvider extends org.yakindu.sct.model.stext.scoping.STextScopeProvider {

}
