/**
 * generated by Xtext
 */
package com.yakindu.sct.domain.scenario.ui.contentassist;

import com.yakindu.sct.domain.scenario.ui.contentassist.AbstractScenarioTextProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ScenarioTextProposalProvider extends AbstractScenarioTextProposalProvider {
}
