/*
 * generated by Xtext
 */
package com.yakindu.sct.domain.scenario.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.yakindu.sct.domain.scenario.services.ScenarioTextGrammarAccess;

public class ScenarioTextParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ScenarioTextGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.yakindu.sct.domain.scenario.parser.antlr.internal.InternalScenarioTextParser createParser(XtextTokenStream stream) {
		return new com.yakindu.sct.domain.scenario.parser.antlr.internal.InternalScenarioTextParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "StateScope";
	}
	
	public ScenarioTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ScenarioTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
