/*
 * generated by Xtext
 */
package com.yakindu.sct.domain.scenario.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ScenarioTextAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/yakindu/sct/domain/scenario/parser/antlr/internal/InternalScenarioText.tokens");
	}
}
