/*
 * generated by Xtext
 */
package com.yakindu.sct.domain.scenario.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.yakindu.sct.domain.scenario.ui.internal.ScenarioTextActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ScenarioTextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ScenarioTextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ScenarioTextActivator.getInstance().getInjector(ScenarioTextActivator.COM_YAKINDU_SCT_DOMAIN_SCENARIO_SCENARIOTEXT);
	}
	
}
