/*
 * generated by Xtext
 */
package com.yakindu.sct.domain.scenario.validation;

import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;
import org.yakindu.base.expressions.validation.ExpressionsJavaValidator;
import org.yakindu.sct.model.sgraph.validation.SCTResourceValidator;
import org.yakindu.sct.model.sgraph.validation.SGraphJavaValidator;
import org.yakindu.sct.model.stext.stext.StextPackage;
import org.yakindu.sct.model.stext.validation.STextJavaValidator;

import com.yakindu.sct.domain.scenario.scenariotext.ScenarioTextPackage;

@ComposedChecks(validators = { STextJavaValidator.class, SGraphJavaValidator.class, SCTResourceValidator.class,
		ExpressionsJavaValidator.class })

public class ScenarioTextJavaValidator
		extends com.yakindu.sct.domain.scenario.validation.AbstractScenarioTextJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(ScenarioTextPackage.eINSTANCE);
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.yakindu.org/sct/sgraph/2.0.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.yakindu.org/base/base/2.0.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.yakindu.org/base/types/2.0.0"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.yakindu.org/base/expressions/Expressions"));
		result.add(StextPackage.eINSTANCE);
		return result;
	}
}
