/*
 * generated by Xtext
 */
package com.yakindu.sct.domain.scenario.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractScenarioTextJavaValidator extends org.yakindu.sct.model.stext.validation.STextJavaValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.yakindu.sct.domain.scenario.scenarioText.ScenarioTextPackage.eINSTANCE);
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.yakindu.org/sct/sgraph/2.0.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.yakindu.org/base/base/2.0.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.yakindu.org/base/types/2.0.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.yakindu.org/base/expressions/Expressions"));
		return result;
	}

}
